const productCategories = [
  { label: "Laminates", href: "/products" },
  { label: "Panels", href: "/products" },
  { label: "Solid Surfaces", href: "/products" },
  { label: "FABWOOD", href: "/products" },
  { label: "Fiber Boards", href: "/products" },
  { label: "Chip Boards", href: "/products" },
  { label: "Value Added Boards", href: "/products" },
  { label: "Boards", href: "/products" },
  { label: "Doors", href: "/products" },
  { label: "Veneer Laminates", href: "/products" },
  { label: "MFC", href: "/products" },
  { label: "CenturyLaminates", href: "/brand/centuryply/laminates" },
  { label: "CenturyVeneers", href: "/brand/centuryply/veneers" },
  { label: "CenturyDoors", href: "/brand/centuryply/doors" },
];

const productSubCategories = [
  { label: "Merino Laminates", href: "/brand/merino/laminate" },
  { label: "CAARA", href: "/products" },
  { label: "High Gloss Laminates", href: "/products" },
  { label: "Modular Furniture Laminates", href: "/products" },
  { label: "Panel Boards", href: "/products" },
  { label: "Merino Hanex", href: "/products" },
  { label: "Fabwood HFSS", href: "/products" },
  { label: "Product Application", href: "/products" },
  { label: "MDF Board", href: "/products" },
  { label: "CARB MDF", href: "/products" },
  { label: "HDMR-MAX", href: "/products" },
  { label: "Boiltough BWP-HDF-FR", href: "/products" },
  { label: "Particle Board", href: "/products" },
  { label: "Crystal UV Gloss Panels", href: "/products" },
  { label: "UHD Acrylic Panels", href: "/products" },
  { label: "Feather Touch Matt Panels", href: "/products" },
  { label: "HDHMR Board", href: "/products" },
  { label: "Moist Master Board", href: "/products" },
  { label: "Boilo BWP-FR-HDF Board", href: "/products" },
  { label: "HDHMR Doors", href: "/products" },
  { label: "Acrylic Gloss Board", href: "/products" },
  { label: "UV High Gloss Board", href: "/products" },
  { label: "Ornate Board", href: "/products" },
  { label: "HPL", href: "/products" },
  { label: "HD Gloss", href: "/products" },
  { label: "Digital/Custom", href: "/products" },
  { label: "Unicore", href: "/products" },
  { label: "Infinia Countertop", href: "/products" },
  { label: "Chalk Grade", href: "/products" },
  { label: "Marker Grade", href: "/products" },
  { label: "Fire Retardant", href: "/products" },
  { label: "ESD Laminates", href: "/products" },
  { label: "Door Special", href: "/products" },
  { label: "Countertop", href: "/products" },
  { label: "VRB", href: "/products" },
  { label: "Four X Ten", href: "/products" },
  { label: "Door Laminates", href: "/products" },
  { label: "New Arrivals", href: "/products" },
  { label: "Lexus Collection (1.50 mm)", href: "/products" },
  { label: "Mikasa Decowood Veneers - New Arrival", href: "/products" },
  { label: "Mikasa Decowood Veneers - Artista", href: "/products" },
  { label: "Mikasa Decowood Veneers - Natural", href: "/products" },
  { label: "Mikasa Decowood Veneers - The Specials", href: "/products" },
  { label: "Mikasa Decowood Veneers - Engineered", href: "/products" },
  { label: "Mikasa Decowood Veneers - Teak", href: "/products" },
  { label: "Mikasa Decowood Veneers - Rainbow", href: "/products" },
  { label: "MFC Core", href: "/products" },
  { label: "MFC Core+", href: "/products" },
  { label: "MFC HDHMR", href: "/products" },
  { label: "Lookbook - 1 mm Laminates", href: "/products" },
  { label: "Starline - 0.8 mm Laminates", href: "/products" },
  { label: "LinerPro - 0.72 mm & 0.8 mm Laminates", href: "/products" },
  { label: "Magnum Collection", href: "/products" },
  { label: "NatzuraWoods - Natural Veneers", href: "/products" },
  { label: "SenzuraStyles - Reconstituted Veneers", href: "/products" },
  { label: "Flush Doors", href: "/products" },
  { label: "Panel Moulded Doors", href: "/products" },
  { label: "Decorative Doors", href: "/products" },
];

const productCategoryGroups = [
  {
    label: "Laminates",
    href: "/brand/centuryply/laminates",
    children: [
      "Merino Laminates",
      "CAARA",
      "High Gloss Laminates",
      "Modular Furniture Laminates",
      "HPL",
      "HD Gloss",
      "Digital/Custom",
      "Unicore",
      "Infinia Countertop",
      "Chalk Grade",
      "Marker Grade",
      "Fire Retardant",
      "ESD Laminates",
      "Door Special",
      "Countertop",
      "VRB",
      "Four X Ten",
      "Door Laminates",
      "New Arrivals",
      "Lexus Collection (1.50 mm)",
    ],
  },
  { label: "Panels", href: "/products", children: ["Panel Boards"] },
  { label: "Solid Surfaces", href: "/products", children: ["Merino Hanex"] },
  { label: "FABWOOD", href: "/products", children: ["Fabwood HFSS", "Product Application"] },
  {
    label: "Fiber Boards",
    href: "/brand/centuryply/veneers",
    children: ["MDF Board", "CARB MDF", "HDMR-MAX", "Boiltough BWP-HDF-FR"],
  },
  { label: "Chip Boards", href: "/products", children: ["Particle Board"] },
  {
    label: "Value Added Boards",
    href: "/brand/centuryply/doors",
    children: [
      "Crystal UV Gloss Panels",
      "UHD Acrylic Panels",
      "Feather Touch Matt Panels",
      "Acrylic Gloss Board",
      "UV High Gloss Board",
      "Ornate Board",
    ],
  },
  {
    label: "Boards",
    href: "/products",
    children: ["HDHMR Board", "Particle Board", "Moist Master Board", "MDF Board", "Boilo BWP-FR-HDF Board"],
  },
  { label: "Doors", href: "/products", children: ["HDHMR Doors"] },
  {
    label: "Veneer Laminates",
    href: "/products",
    children: [
      "Mikasa Decowood Veneers - New Arrival",
      "Mikasa Decowood Veneers - Artista",
      "Mikasa Decowood Veneers - Natural",
      "Mikasa Decowood Veneers - The Specials",
      "Mikasa Decowood Veneers - Engineered",
      "Mikasa Decowood Veneers - Teak",
      "Mikasa Decowood Veneers - Rainbow",
    ],
  },
  { label: "MFC", href: "/products", children: ["MFC Core", "MFC Core+", "MFC HDHMR"] },
  {
    label: "CenturyLaminates",
    href: "/brand/centuryply/laminates",
    children: [
      "Lookbook - 1 mm Laminates",
      "Starline - 0.8 mm Laminates",
      "LinerPro - 0.72 mm & 0.8 mm Laminates",
      "Magnum Collection",
    ],
  },
  {
    label: "CenturyVeneers",
    href: "/brand/centuryply/veneers",
    children: ["NatzuraWoods - Natural Veneers", "SenzuraStyles - Reconstituted Veneers"],
  },
  {
    label: "CenturyDoors",
    href: "/brand/centuryply/doors",
    children: ["Flush Doors", "Panel Moulded Doors", "Decorative Doors"],
  },
].map((group) => ({
  ...group,
  children: group.children.map((label) => ({
    label,
    href: {
      "Merino Laminates": "/brand/merino/laminate",
      "Lookbook - 1 mm Laminates": "/brand/centuryply/laminates",
      "Starline - 0.8 mm Laminates": "/brand/centuryply/laminates",
      "LinerPro - 0.72 mm & 0.8 mm Laminates": "/brand/centuryply/laminates",
      "Magnum Collection": "/brand/centuryply/laminates",
      "NatzuraWoods - Natural Veneers": "/brand/centuryply/veneers",
      "SenzuraStyles - Reconstituted Veneers": "/brand/centuryply/veneers",
      "Flush Doors": "/brand/centuryply/doors",
      "Panel Moulded Doors": "/brand/centuryply/doors",
      "Decorative Doors": "/brand/centuryply/doors",
    }[label] || "/products",
  })),
}));

const brands = [
  { label: "Merino", href: "/brand/merino" },
  { label: "Crossbond", href: "/products" },
  { label: "Action Tesa", href: "/brand/action-tesa" },
  { label: "Greenlam", href: "/brand/greenlam" },
  { label: "CenturyPly", href: "/brand/centuryply" },
];


const quickLinks = [
  { label: "About Us", href: "/default/about-us" },
  { label: "Infrastructure", href: "/default/our-projects" },
  { label: "Gallery", href: "/default/news" },
  { label: "Career", href: "/default/our-team" },
  { label: "Contact Us", href: "/default/contact-us" },
];

const applications = [
  { label: "Kitchen", href: "/products" },
  { label: "Wardrobe", href: "/products" },
  { label: "Kids Room", href: "/products" },
  { label: "Living Room", href: "/products" },
  { label: "Doors", href: "/products" },
];

const footerData = {
  productCategories,
  productSubCategories,
  productCategoryGroups,
  brands,
  quickLinks,
  applications,
};

module.exports = footerData;
